/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_PoseEstimation */

#ifndef _Included_com_seeta_sdk_PoseEstimation
#define _Included_com_seeta_sdk_PoseEstimation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_PoseEstimation
 * Method:    construct
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_PoseEstimation_construct
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_PoseEstimation
 * Method:    poseEstimate
 * Signature: (JIII[B[I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_seeta_sdk_PoseEstimation_poseEstimate
  (JNIEnv *, jobject, jlong, jint, jint, jint, jbyteArray, jintArray);

/*
 * Class:     com_seeta_sdk_PoseEstimation
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_PoseEstimation_release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
