/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dnak_rkcodec_Rkcodec */

#ifndef _Included_com_dnak_rkcodec_Rkcodec
#define _Included_com_dnak_rkcodec_Rkcodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dnak_rkcodec_Rkcodec
 * Method:    convert
 * Signature: ([BI[BIII)V
 */

JNIEXPORT void JNICALL Java_com_dnak_rkcodec_Rkcodec_convert
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
